[workspace]
members = [
    "do-proxy", 
    "examples/*"
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1"
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
worker = "0.0.12"