[package]
name = "inserter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
do-proxy = { path = "../../do-proxy" }
serde = { workspace = true }
serde_json = { workspace = true }
worker = { workspace = true }